var namespace_orange_bug_reloaded_1_1_core =
[
    [ "Entities", "namespace_orange_bug_reloaded_1_1_core_1_1_entities.html", "namespace_orange_bug_reloaded_1_1_core_1_1_entities" ],
    [ "Events", "namespace_orange_bug_reloaded_1_1_core_1_1_events.html", "namespace_orange_bug_reloaded_1_1_core_1_1_events" ],
    [ "Rendering", "namespace_orange_bug_reloaded_1_1_core_1_1_rendering.html", "namespace_orange_bug_reloaded_1_1_core_1_1_rendering" ],
    [ "Tiles", "namespace_orange_bug_reloaded_1_1_core_1_1_tiles.html", "namespace_orange_bug_reloaded_1_1_core_1_1_tiles" ],
    [ "Transactions", "namespace_orange_bug_reloaded_1_1_core_1_1_transactions.html", "namespace_orange_bug_reloaded_1_1_core_1_1_transactions" ],
    [ "Chunk", "class_orange_bug_reloaded_1_1_core_1_1_chunk.html", "class_orange_bug_reloaded_1_1_core_1_1_chunk" ],
    [ "ChunkLoader", "class_orange_bug_reloaded_1_1_core_1_1_chunk_loader.html", "class_orange_bug_reloaded_1_1_core_1_1_chunk_loader" ],
    [ "Entity", "class_orange_bug_reloaded_1_1_core_1_1_entity.html", "class_orange_bug_reloaded_1_1_core_1_1_entity" ],
    [ "EntityEventArgs", "class_orange_bug_reloaded_1_1_core_1_1_entity_event_args.html", "class_orange_bug_reloaded_1_1_core_1_1_entity_event_args" ],
    [ "FollowUpEventArgs", "class_orange_bug_reloaded_1_1_core_1_1_follow_up_event_args.html", "class_orange_bug_reloaded_1_1_core_1_1_follow_up_event_args" ],
    [ "GameEventArgs", "class_orange_bug_reloaded_1_1_core_1_1_game_event_args.html", "class_orange_bug_reloaded_1_1_core_1_1_game_event_args" ],
    [ "IChunk", "interface_orange_bug_reloaded_1_1_core_1_1_i_chunk.html", "interface_orange_bug_reloaded_1_1_core_1_1_i_chunk" ],
    [ "IChunkStorage", "interface_orange_bug_reloaded_1_1_core_1_1_i_chunk_storage.html", "interface_orange_bug_reloaded_1_1_core_1_1_i_chunk_storage" ],
    [ "IGameplayMap", "interface_orange_bug_reloaded_1_1_core_1_1_i_gameplay_map.html", "interface_orange_bug_reloaded_1_1_core_1_1_i_gameplay_map" ],
    [ "IMap", "interface_orange_bug_reloaded_1_1_core_1_1_i_map.html", "interface_orange_bug_reloaded_1_1_core_1_1_i_map" ],
    [ "IMapMetadata", "interface_orange_bug_reloaded_1_1_core_1_1_i_map_metadata.html", null ],
    [ "InMemoryChunkStorage", "class_orange_bug_reloaded_1_1_core_1_1_in_memory_chunk_storage.html", "class_orange_bug_reloaded_1_1_core_1_1_in_memory_chunk_storage" ],
    [ "INotifyCollectionChanged", "interface_orange_bug_reloaded_1_1_core_1_1_i_notify_collection_changed.html", "interface_orange_bug_reloaded_1_1_core_1_1_i_notify_collection_changed" ],
    [ "IReadOnlyChunk", "interface_orange_bug_reloaded_1_1_core_1_1_i_read_only_chunk.html", "interface_orange_bug_reloaded_1_1_core_1_1_i_read_only_chunk" ],
    [ "IReadOnlyMap", "interface_orange_bug_reloaded_1_1_core_1_1_i_read_only_map.html", "interface_orange_bug_reloaded_1_1_core_1_1_i_read_only_map" ],
    [ "ISupportsMove", "interface_orange_bug_reloaded_1_1_core_1_1_i_supports_move.html", "interface_orange_bug_reloaded_1_1_core_1_1_i_supports_move" ],
    [ "Map", "class_orange_bug_reloaded_1_1_core_1_1_map.html", "class_orange_bug_reloaded_1_1_core_1_1_map" ],
    [ "MapDependencyAttribute", "class_orange_bug_reloaded_1_1_core_1_1_map_dependency_attribute.html", null ],
    [ "MapDependencyTable", "class_orange_bug_reloaded_1_1_core_1_1_map_dependency_table.html", "class_orange_bug_reloaded_1_1_core_1_1_map_dependency_table" ],
    [ "ObservableCollection", "class_orange_bug_reloaded_1_1_core_1_1_observable_collection.html", "class_orange_bug_reloaded_1_1_core_1_1_observable_collection" ],
    [ "ObservableDictionary", "class_orange_bug_reloaded_1_1_core_1_1_observable_dictionary.html", "class_orange_bug_reloaded_1_1_core_1_1_observable_dictionary" ],
    [ "Point", "struct_orange_bug_reloaded_1_1_core_1_1_point.html", "struct_orange_bug_reloaded_1_1_core_1_1_point" ],
    [ "PointConverter", "class_orange_bug_reloaded_1_1_core_1_1_point_converter.html", "class_orange_bug_reloaded_1_1_core_1_1_point_converter" ],
    [ "Rectangle", "struct_orange_bug_reloaded_1_1_core_1_1_rectangle.html", "struct_orange_bug_reloaded_1_1_core_1_1_rectangle" ],
    [ "RectangleConverter", "class_orange_bug_reloaded_1_1_core_1_1_rectangle_converter.html", "class_orange_bug_reloaded_1_1_core_1_1_rectangle_converter" ],
    [ "Reflector", "class_orange_bug_reloaded_1_1_core_1_1_reflector.html", "class_orange_bug_reloaded_1_1_core_1_1_reflector" ],
    [ "Tile", "class_orange_bug_reloaded_1_1_core_1_1_tile.html", "class_orange_bug_reloaded_1_1_core_1_1_tile" ],
    [ "TileEventArgs", "class_orange_bug_reloaded_1_1_core_1_1_tile_event_args.html", "class_orange_bug_reloaded_1_1_core_1_1_tile_event_args" ]
];