var searchData=
[
  ['iaudiohint',['IAudioHint',['../interface_orange_bug_reloaded_1_1_core_1_1_rendering_1_1_i_audio_hint.html',1,'OrangeBugReloaded::Core::Rendering']]],
  ['ichunk',['IChunk',['../interface_orange_bug_reloaded_1_1_core_1_1_i_chunk.html',1,'OrangeBugReloaded::Core']]],
  ['ichunkstorage',['IChunkStorage',['../interface_orange_bug_reloaded_1_1_core_1_1_i_chunk_storage.html',1,'OrangeBugReloaded::Core']]],
  ['igameevent',['IGameEvent',['../interface_orange_bug_reloaded_1_1_core_1_1_events_1_1_i_game_event.html',1,'OrangeBugReloaded::Core::Events']]],
  ['igameeventemitter',['IGameEventEmitter',['../interface_orange_bug_reloaded_1_1_core_1_1_events_1_1_i_game_event_emitter.html',1,'OrangeBugReloaded::Core::Events']]],
  ['igameplaymap',['IGameplayMap',['../interface_orange_bug_reloaded_1_1_core_1_1_i_gameplay_map.html',1,'OrangeBugReloaded::Core']]],
  ['imap',['IMap',['../interface_orange_bug_reloaded_1_1_core_1_1_i_map.html',1,'OrangeBugReloaded::Core']]],
  ['imapmetadata',['IMapMetadata',['../interface_orange_bug_reloaded_1_1_core_1_1_i_map_metadata.html',1,'OrangeBugReloaded::Core']]],
  ['imaptransaction',['IMapTransaction',['../interface_orange_bug_reloaded_1_1_core_1_1_transactions_1_1_i_map_transaction.html',1,'OrangeBugReloaded::Core::Transactions']]],
  ['imaptransactionwithmovesupport',['IMapTransactionWithMoveSupport',['../interface_orange_bug_reloaded_1_1_core_1_1_transactions_1_1_i_map_transaction_with_move_support.html',1,'OrangeBugReloaded::Core::Transactions']]],
  ['inktile',['InkTile',['../class_orange_bug_reloaded_1_1_core_1_1_tiles_1_1_ink_tile.html',1,'OrangeBugReloaded::Core::Tiles']]],
  ['inktileconsumeevent',['InkTileConsumeEvent',['../class_orange_bug_reloaded_1_1_core_1_1_tiles_1_1_ink_tile_consume_event.html',1,'OrangeBugReloaded::Core::Tiles']]],
  ['inmemorychunkstorage',['InMemoryChunkStorage',['../class_orange_bug_reloaded_1_1_core_1_1_in_memory_chunk_storage.html',1,'OrangeBugReloaded::Core']]],
  ['inotifycollectionchanged',['INotifyCollectionChanged',['../interface_orange_bug_reloaded_1_1_core_1_1_i_notify_collection_changed.html',1,'OrangeBugReloaded::Core']]],
  ['ireadonlychunk',['IReadOnlyChunk',['../interface_orange_bug_reloaded_1_1_core_1_1_i_read_only_chunk.html',1,'OrangeBugReloaded::Core']]],
  ['ireadonlymap',['IReadOnlyMap',['../interface_orange_bug_reloaded_1_1_core_1_1_i_read_only_map.html',1,'OrangeBugReloaded::Core']]],
  ['ireadonlymaptransaction',['IReadOnlyMapTransaction',['../interface_orange_bug_reloaded_1_1_core_1_1_transactions_1_1_i_read_only_map_transaction.html',1,'OrangeBugReloaded::Core::Transactions']]],
  ['isupportsmove',['ISupportsMove',['../interface_orange_bug_reloaded_1_1_core_1_1_i_supports_move.html',1,'OrangeBugReloaded::Core']]],
  ['itrigger',['ITrigger',['../interface_orange_bug_reloaded_1_1_core_1_1_tiles_1_1_i_trigger.html',1,'OrangeBugReloaded::Core::Tiles']]],
  ['ivisualhint',['IVisualHint',['../interface_orange_bug_reloaded_1_1_core_1_1_rendering_1_1_i_visual_hint.html',1,'OrangeBugReloaded::Core::Rendering']]]
];
